Controllers/RootController.cs
using Microsoft.AspNetCore.Mvc;
using Short.er.Models;
using System.Diagnostics;

namespace Short.er.Controllers {
  public class RootController : Controller {

    private readonly ILogger<RootController> _logger;

    public RootController(ILogger<RootController> logger) {
      _logger = logger;
    }
    [Route("")]
    public IActionResult Index() {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error() {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

Controllers/ShortenedUrlsController.cs
using System.Diagnostics;
using System.Security.Claims;
using System.Security.Cryptography;
using Amazon.AspNetCore.Identity.Cognito;
using Amazon.Extensions.CognitoAuthentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Short.er.Data;
using Short.er.Models;
using Short.er.Utils;

namespace Short.er.Controllers {
	public class ShortenedUrlsController : Controller {
		private readonly ApplicationDBContext _context;
		private readonly CognitoUserManager<CognitoUser> _userManager;

		public ShortenedUrlsController(ApplicationDBContext context,
		UserManager<CognitoUser> userManager) {
			_context = context;
			_userManager = userManager as CognitoUserManager<CognitoUser>;
		}

		// GET: ShortenedUrls
		[Route("/ShortenedUrls")]
		public async Task<IActionResult> Index() {
			string userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name).Value;

			List<ShortenedUrl> content = await _context.Urls
					.Where(entry => entry.UserId
					== userId)
					.ToListAsync();

			return _context.Urls != null ?
						View(content) :
						Problem("Entity set 'ApplicationDBContext.Urls'  is null.");
		}

		// GET: ShortenedUrls/Details/5
		public async Task<IActionResult> Details(int? id) {
			if (id == null || _context.Urls == null) {
				return NotFound();
			}

			var shortenedUrl = await _context.Urls
				.FirstOrDefaultAsync(m => m.Id == id);
			if (shortenedUrl == null) {
				return NotFound();
			}

			return View(shortenedUrl);
		}

		// GET: ShortenedUrls/Create

		public IActionResult Create() {
			return View();
		}

		// POST: ShortenedUrls/Create
		[Route("/ShortenedUrls/Create")]
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ShortenedUrl shortenedUrl) {
			string input = StringUtils.RemoveBadChars(shortenedUrl.Url);
			SHA1 hasher = SHA1.Create();
			string hash = HashUtils.GetHash(hasher, input);
			/*			Debug.WriteLine($"The SHA256 hash of {input} {input.Length} is: {hash} {hash.Length}.");
						Debug.WriteLine("Verifying the hash...");
						if (HashUtils.VerifyHash(hasher, input, hash)) {
							Debug.WriteLine("The hashes are the same.");
						} else {
							Debug.WriteLine("The hashes are not same.");
						}*/
			string userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name).Value;

			shortenedUrl.Hash = hash;
			shortenedUrl.CreatedDateTime = DateTime.Now;
			shortenedUrl.NumberOfRquests = 0;
			shortenedUrl.UserId = userId;

			Debug.Write(userId);

			TryValidateModel(shortenedUrl);
			if (ModelState.IsValid) {
				_context.Add(shortenedUrl);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(shortenedUrl);
		}

		// GET: ShortenedUrls/Edit/5
		public async Task<IActionResult> Edit(int? id) {
			if (id == null || _context.Urls == null) {
				return NotFound();
			}

			var shortenedUrl = await _context.Urls.FindAsync(id);
			if (shortenedUrl == null) {
				return NotFound();
			}
			return View(shortenedUrl);
		}

		// POST: ShortenedUrls/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Url,Hash,CreatedDateTime,NumberOfRquests")] ShortenedUrl shortenedUrl) {
			if (id != shortenedUrl.Id) {
				return NotFound();
			}

			if (ModelState.IsValid) {
				try {
					_context.Update(shortenedUrl);
					await _context.SaveChangesAsync();
				} catch (DbUpdateConcurrencyException) {
					if (!ShortenedUrlExists(shortenedUrl.Id)) {
						return NotFound();
					} else {
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(shortenedUrl);
		}

		// GET: ShortenedUrls/Delete/5
		public async Task<IActionResult> Delete(int? id) {
			if (id == null || _context.Urls == null) {
				return NotFound();
			}

			var shortenedUrl = await _context.Urls
				.FirstOrDefaultAsync(m => m.Id == id);
			if (shortenedUrl == null) {
				return NotFound();
			}

			return View(shortenedUrl);
		}

		// POST: ShortenedUrls/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id) {
			if (_context.Urls == null) {
				return Problem("Entity set 'ApplicationDBContext.Urls'  is null.");
			}
			var shortenedUrl = await _context.Urls.FindAsync(id);
			if (shortenedUrl != null) {
				_context.Urls.Remove(shortenedUrl);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool ShortenedUrlExists(int id) {
			return (_context.Urls?.Any(e => e.Id == id)).GetValueOrDefault();
		}
	}
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Amazon.Extensions.CognitoAuthentication

@inject SignInManager<CognitoUser> SignInManager
@inject UserManager<CognitoUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Short.er</title>
    <link rel="stylesheet" href="~/assets/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/assets/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Short.er.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Root" asp-action="Index">Short.er</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Root" asp-action="Index">Home</a>
                             @if (SignInManager.IsSignedIn(User))
{
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShortenedUrls" asp-action="Index">Controle Pannel</a>
                        </li>
}
                    </ul>
                </div>
            </div>
     <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end container-fluid">
    <ul class="nav navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
{

            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Hello @UserManager.GetUserName(User)!</a></li>
            <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>


}
else
{
        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
}
    </ul>
    </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Short.er
        </div>
    </footer>
    <script src="~/assets/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/assets/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>